export const CONFIG_NAMESPACES = {
  BULL: 'bull',
  CACHE: 'cache',
  DATABASE: 'database',
  FILE_STORAGE: 'fileStorage',
  JWT: 'jwt',
  KAFKA: 'kafka',
} as const;

export const CONFIG_KEYS = {
  BULL: CONFIG_NAMESPACES.BULL,
  CACHE: CONFIG_NAMESPACES.CACHE,
  CACHE_TTL: `${CONFIG_NAMESPACES.CACHE}.ttl`,
  DATABASE: CONFIG_NAMESPACES.DATABASE,
  FILE_STORAGE: CONFIG_NAMESPACES.FILE_STORAGE,
  JWT_SECRET: `${CONFIG_NAMESPACES.JWT}.secret`,
  KAFKA_BROKERS: `${CONFIG_NAMESPACES.KAFKA}.brokers`,
} as const;

export const ENV_KEYS = {
  JWT_SECRET: 'JWT_SECRET',
  REDIS_TTL: 'REDIS_TTL',
  REDIS_ADDRESS: 'REDIS_ADDRESS',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
  MINIO_ENDPOINT: 'MINIO_ENDPOINT',
  MINIO_REGION: 'MINIO_REGION',
  MINIO_ACCESS_KEY: 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY: 'MINIO_SECRET_KEY',
  MINIO_BUCKET_NAME: 'MINIO_BUCKET_NAME',
  MONGO_URI: 'MONGO_URI',
  MONGO_DB: 'MONGO_DB',
  NAUTHJ_PORT: 'NAUTHJ_PORT',
  NOTIFICATION_SERVICE_PORT: 'NOTIFICATION_SERVICE_PORT',
  KAFKA_BROKERS: 'KAFKA_BROKERS',
} as const;
