export const INJECTION_TOKENS = {
  DATA_SOURCE: 'DATA_SOURCE',
  DATABASE_CONNECTION: 'DATABASE_CONNECTION',
  USER_REPOSITORY: 'USER_REPOSITORY',
  PAYMENT_REPOSITORY: 'PAYMENT_REPOSITORY',
  AVATAR_REPOSITORY: 'AVATAR_REPOSITORY',
  NOTIFICATION_MODEL: 'NOTIFICATION_MODEL',
  PAYMENT_SERVICE: 'PAYMENT_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
} as const;
